apiVersion: v2
name: istio
version: 1.0.0
dependencies:
  - name: base
    version: 1.24.3
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: 1.24.3
    repository: https://istio-release.storage.googleapis.com/charts
