{{- if and (and .Values.cloudflare.account .Values.cloudflare.tunnelId .Values.cloudflare.tunnelSecret) }}
apiVersion: v1
kind: Namespace
metadata:
  name: mgmt

---

apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
  namespace: mgmt
type: Opaque

stringData:
  credentials.json: |-
    {
      "AccountTag": {{ .Values.cloudflare.account | quote }},
      "TunnelID": {{ .Values.cloudflare.tunnelId | quote }},
      "TunnelSecret": {{ .Values.cloudflare.tunnelSecret | quote }}
    }
{{- end }}