apiVersion: v1
kind: Namespace
metadata:
  name: argocd

---

apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: "{{ .Values.github.repo }}"
  username: "{{ .Values.github.user }}"
  password: {{ .Values.github.pat }}
