apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{.Values.name}}"
spec:
  secretName: "{{.Values.name}}"
  issuerRef:
    kind: ClusterIssuer
    name: "tls-issuer"
  commonName: "*.{{ .Values.domain }}"
  dnsNames:
    - "*.{{ .Values.domain }}"
    - "{{ .Values.domain }}"
