
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Release.Name }}"
spec:
  hosts:
  - "{{ .Values.subdomain }}.{{ .Values.domain }}"
  gateways:
  - istio-ingress/mgmt-gateway
  http:
  - route:
    - destination:
        host: {{ .Release.Name }}.mgmt.svc.cluster.local
        port:
          number: 19999
