apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quota-limit-cluster-role
rules:
- apiGroups: [""]
  resources: ["resourcequotas", "limitranges"]
  verbs: ["create"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: create-quota-limit-global
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: quota-limit-cluster-role
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argocd