{{- if .Values.hostname }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd
spec:
  hosts:
  - "{{ .Values.hostname }}"
  gateways:
  - istio-ingress/mgmt-gateway
  http:
  - route:
    - destination:
        host: argo-cd-argocd-server.argocd.svc.cluster.local
        port:
          number: 80
{{ end }}
