{{- define "system.argo.values" }}
foo: bar
{{- end }}

{{- $merged := merge (deepCopy .Values) (deepCopy (default (dict) .Values.global)) -}}
{{- $values := include "system.argo.values" $merged | fromYaml }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: system
  source:
    path: charts/system/argo-cd
    repoURL: "{{ $merged.repo }}"
    helm:
      values: {{ $values | toJson | quote }}
    targetRevision: "{{ $merged.revision }}"
  syncPolicy:
    syncOptions:
     - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    automated:
      prune: true
      selfHeal: true
