{{- $merged := merge (deepCopy .Values) (deepCopy (default (dict) .Values.global)) -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  project: system
  source:
    path: charts/system/cert-manager
    repoURL: "{{ $merged.repo }}"
    targetRevision: "{{ $merged.revision }}"
  syncPolicy:
    syncOptions:
     - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true