apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: system
  ignoreDifferences:
    - group: "*"
      kind: "*"
      jqPathExpressions:
        - '.webhooks[]?.failurePolicy'

  source:
    path: charts/system/istio
    repoURL: "{{ .Values.repo }}"
    targetRevision: "{{ .Values.revision }}"
  syncPolicy:
    syncOptions:
     - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
  project: system
  source:
    path: charts/system/istio-gateway-controller
    repoURL: "{{ .Values.repo }}"
    targetRevision: "{{ .Values.revision }}"
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    syncOptions:
     - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
