{{- $merged := merge (deepCopy .Values) (deepCopy (default (dict) .Values.global)) -}}

{{- if eq $merged.loadbalancer.enabled true }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  project: system
  source:
    path: charts/system/metallb
    repoURL: "{{ $merged.repo }}"
    helm:
      values: {{ $merged.loadbalancer | toJson | quote }}
    targetRevision: "{{ $merged.revision }}"
  syncPolicy:
    syncOptions:
     - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

{{ end }}