{{- define "system.istio.mgmt-gateway" }}
domain: {{ .Values.mgmt.domain }}
name: mgmt-gateway
{{- end }}

{{- if eq .Values.mgmt.enabled true }}
{{- $gateway := include "system.istio.mgmt-gateway" . | fromYaml }}

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mgmt
  namespace: argocd
spec:
  destinations:
    - namespace: '!kube-system'
      server: '*'
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  sourceRepos:
    - "{{ .Values.repo }}"

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-mgmt-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
  project: system
  source:
    path: charts/system/istio-gateway
    repoURL: "{{ .Values.repo }}"
    targetRevision: "{{ .Values.revision }}"
    helm:
      values: {{ $gateway | toJson | quote }}
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    syncOptions:
     - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

---


kind: Namespace
apiVersion: v1
metadata:
  name: mgmt
  labels:
    istio-injection: enabled

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "mgmt"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: system
  source:
    path: charts/system/namespace
    repoURL: "{{ .Values.repo }}"
    targetRevision: "{{ .Values.revision }}"
    helm:
      values: {{ toJson (dict "domain" .Values.mgmt.domain) | quote }}
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    syncOptions:
     - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

{{- end }}
