{{- $merged := merge (deepCopy .Values) (deepCopy (default (dict) .Values.global)) -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: system
  source:
    path: apps
    repoURL: "{{ $merged.repo }}"
    targetRevision: "{{ $merged.revision }}"
    helm:
      values: {{ dict "global" .Values.global | toJson | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
