{{- define "mgmt.uptimekuma.values" }}
domain: {{ .Values.mgmt.domain }}
{{- end }}

{{- if eq .Values.mgmt.enabled true }}
{{- $value := include "mgmt.uptimekuma.values" . | fromYaml }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: mgmt
  project: mgmt
  source:
    path: charts/mgmt/uptime-kuma
    repoURL: "{{ .Values.repo }}"
    helm:
      values: {{ $value | toJson | quote }}
    targetRevision: "{{ .Values.revision }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}