apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "{{ .Values.name }}"
  namespace: argocd
spec:
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
