{{- range $key, $value := .Values.volumes }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "shared-{{ $key }}"
  labels:
    storage: "shared-{{ $key }}"
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-class
  mountOptions:
    - hard
  nfs:
    path: "{{ $value.path }}"
    server: "{{ $value.server }}"

---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "shared-{{ $key }}"
spec:
  storageClassName: nfs-class
  accessModes:
    - "{{ $value.accessMode | default "ReadWriteMany" }}"
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      storage: "shared-{{ $key }}"

---
{{- end }}