apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Release.Name }}-app-data"
  labels:
    storage: "{{ .Release.Name }}-app-data"
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-class
  mountOptions:
    - hard
  nfs:
    path: "{{ .Values.nfs.path }}"
    server: "{{ .Values.nfs.server }}"

---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-app-data"
spec:
  storageClassName: nfs-class
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      storage: "{{ .Release.Name }}-app-data"

---
