apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: duplicati-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-duplicati-deployment"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-duplicati-pod"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-duplicati-pod"
    spec:
      containers:
        - image: lscr.io/linuxserver/duplicati:2.0.7
          imagePullPolicy: Always
          name: "{{ .Release.Name }}-duplicati"
          env:
            - name: PUID
              value: '0'
            - name: PGID
              value: '0'
            - name: TZ
              value: Europe/Amsterdam
          ports:
            - containerPort: 8200
          volumeMounts:
            - mountPath: /configs
              name: data 
      volumes:
        - name: data 
          persistentVolumeClaim:
            claimName: "duplicati-data"

---

apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-duplicati-svc"
spec:
  ports:
    - port: 80
      targetPort: 8200
      protocol: TCP
  selector:
    app: "{{ .Release.Name }}-duplicati-pod"

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-duplicati-ingress"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "*.{{ .Values.domain }}"
        - "{{ .Values.domain }}"
      secretName: "tls-secret"
  rules:
    - host: "{{ .Values.subdomain }}.{{ .Values.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-duplicati-svc"
                port:
                  number: 80