cloudflare:
  token: not-set
  account: "e8dd6004912643708a4fe028b3d5a333"
  tunnelId: "cc0de988-2112-41d1-af06-e03ac05fe756"
github:
  repo: https://github.com/morten-olsen/homelab
  user: morten-olsen
  pat: not-set
imageCredentials:
  registry: ghcr.io
