apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-data"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-pod"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-pod"
    spec:
      containers:
        - image: louislam/uptime-kuma:1.23.11-alpine
          imagePullPolicy: Always
          name: "{{ .Release.Name }}"
          ports:
            - containerPort: 3001
          volumeMounts:
            - mountPath: /app/data
              name: data 
      volumes:
        - name: data 
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-data"

---

apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-svc"
spec:
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
  selector:
    app: "{{ .Release.Name }}-pod"

