global: {}
repo: https://github.com/morten-olsen/homelab
revision: next
name: local
envs:
  mgmt:
    enabled: true
    domain: mgmt.local.olsen.cloud
    apps:
      mgmt:
        repo: https://github.com/morten-olsen/homelab-mgmt
        path: apps
        revision: main
        values: {}
    volumes: {}
argo: {}
loadbalancer:
  enabled: true
  ipRange: 172.18.255.200-172.18.255.250
storage:
  nfs:
    host: 192.168.20.106
    path: /mnt/HDD/Apps
