apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-ip
spec:
  addresses:
  - "{{.Values.ipRange}}"
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty