{{- if .Values.domain }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-secret
  namespace: {{ .Values.namespace }}
spec:
  secretName: tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: "tls-issuer"
  commonName: "*.{{ .Values.domain }}"
  dnsNames:
    - "*.{{ .Values.domain }}"
    - "{{ .Values.domain }}"
{{ end }}