apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    {{- if .Values.domain }}
    "domain": {{ .Values.domain }} 
    {{ end }}
