{{- if eq .Values.quota.enabled true }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  hard:
    {{ toYaml .Values.quota.hard | indent 4 }}
{{- end }}