apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}"
    spec:
      containers:
        - image: lscr.io/linuxserver/duplicati:2.1.0
          imagePullPolicy: Always
          name: "{{ .Release.Name }}"
          env:
            - name: PUID
              value: '0'
            - name: PGID
              value: '0'
            - name: TZ
              value: Europe/Amsterdam
          ports:
            {{- range $key, $value := .Values.rules }}
            - containerPort: {{ $value.nodePort }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: "/etc/foo"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: "{{ .Release.Name }}"
