{{- range $key, $value := .Values.ports }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Release.Name }}-{{ $key }}"
spec:
  type: LoadBalancer
  ports:
    - port: {{ $value.port }}
      targetPort: {{ $value.containerPort }}
      nodePort: {{ $value.nodePort }}
      protocol: TCP
  selector:
    app: "{{ $.Release.Name }}"
---
{{- end}}
